// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/asdp/asdp.proto

package asdp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentDataPlaneService_Connect_FullMethodName = "/agentscope.protocol.v1.AgentDataPlaneService/Connect"
)

// AgentDataPlaneServiceClient is the client API for AgentDataPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentDataPlaneService is the ASDP gRPC service.
// Single bidirectional stream multiplexing all message types (analogous to xDS ADS).
type AgentDataPlaneServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Upstream, Downstream], error)
}

type agentDataPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentDataPlaneServiceClient(cc grpc.ClientConnInterface) AgentDataPlaneServiceClient {
	return &agentDataPlaneServiceClient{cc}
}

func (c *agentDataPlaneServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Upstream, Downstream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentDataPlaneService_ServiceDesc.Streams[0], AgentDataPlaneService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Upstream, Downstream]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentDataPlaneService_ConnectClient = grpc.BidiStreamingClient[Upstream, Downstream]

// AgentDataPlaneServiceServer is the server API for AgentDataPlaneService service.
// All implementations must embed UnimplementedAgentDataPlaneServiceServer
// for forward compatibility.
//
// AgentDataPlaneService is the ASDP gRPC service.
// Single bidirectional stream multiplexing all message types (analogous to xDS ADS).
type AgentDataPlaneServiceServer interface {
	Connect(grpc.BidiStreamingServer[Upstream, Downstream]) error
	mustEmbedUnimplementedAgentDataPlaneServiceServer()
}

// UnimplementedAgentDataPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentDataPlaneServiceServer struct{}

func (UnimplementedAgentDataPlaneServiceServer) Connect(grpc.BidiStreamingServer[Upstream, Downstream]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentDataPlaneServiceServer) mustEmbedUnimplementedAgentDataPlaneServiceServer() {}
func (UnimplementedAgentDataPlaneServiceServer) testEmbeddedByValue()                               {}

// UnsafeAgentDataPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentDataPlaneServiceServer will
// result in compilation errors.
type UnsafeAgentDataPlaneServiceServer interface {
	mustEmbedUnimplementedAgentDataPlaneServiceServer()
}

func RegisterAgentDataPlaneServiceServer(s grpc.ServiceRegistrar, srv AgentDataPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentDataPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentDataPlaneService_ServiceDesc, srv)
}

func _AgentDataPlaneService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentDataPlaneServiceServer).Connect(&grpc.GenericServerStream[Upstream, Downstream]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentDataPlaneService_ConnectServer = grpc.BidiStreamingServer[Upstream, Downstream]

// AgentDataPlaneService_ServiceDesc is the grpc.ServiceDesc for AgentDataPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentDataPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentscope.protocol.v1.AgentDataPlaneService",
	HandlerType: (*AgentDataPlaneServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentDataPlaneService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/asdp/asdp.proto",
}
