/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.extensions.mysql.snapshot;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.sql.DataSource;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;

/**
 * Unit tests for the snapshot table DDL generated by {@link JdbcRemoteSnapshotClient}.
 *
 * <p>{@code snapshot_id} is the primary key and a caller-supplied identifier, so its collation is the
 * difference between two ids differing only in letter case being two rows or one — with the second
 * upload silently overwriting the first. This unit suite runs without a live MySQL server and
 * asserts the DDL that is actually issued; the runtime behaviour is covered by the
 * testcontainers-based {@code MysqlIntegrationTest} (mysql:8.0) in agentscope-extensions-jdbc.
 */
@DisplayName("JdbcRemoteSnapshotClient snapshot table DDL")
class JdbcRemoteSnapshotClientTest {

    @Test
    @DisplayName("auto-created snapshot table pins a binary collation on the primary key")
    void initSchemaPinsBinaryCollation() throws Exception {
        String ddl = capturedInitDdl();

        assertTrue(
                ddl.contains("snapshot_id VARCHAR(512) COLLATE utf8mb4_bin NOT NULL PRIMARY KEY"),
                () -> "snapshot_id is not case-sensitive in: " + ddl);
        // The table states its charset and engine as well, so the payload column does not depend on
        // whatever the schema default happens to be.
        assertTrue(ddl.contains("data LONGBLOB NOT NULL"));
        assertTrue(ddl.contains("ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC"));
    }

    @Test
    @DisplayName("only the key column is case-sensitive; the payload is left on the table default")
    void payloadStaysOnTableDefault() throws Exception {
        String ddl = capturedInitDdl();

        assertTrue(ddl.contains("data LONGBLOB NOT NULL"), () -> "unexpected payload DDL: " + ddl);
        assertFalse(
                ddl.contains("LONGBLOB COLLATE"),
                () -> "collation leaked onto the payload column: " + ddl);
    }

    /** Runs the constructor with schema initialization on and returns the DDL it executed. */
    private static String capturedInitDdl() throws SQLException {
        DataSource dataSource = mock(DataSource.class);
        Connection connection = mock(Connection.class);
        Statement statement = mock(Statement.class);
        when(dataSource.getConnection()).thenReturn(connection);
        when(connection.createStatement()).thenReturn(statement);

        new JdbcRemoteSnapshotClient(dataSource, true);

        ArgumentCaptor<String> ddlCaptor = ArgumentCaptor.forClass(String.class);
        verify(statement).execute(ddlCaptor.capture());
        return ddlCaptor.getValue().replaceAll("\\s+", " ").trim();
    }
}
