/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.extensions.model.ollama.dto;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Ollama chat message DTO.
 * Represents a message in the conversation history.
 *
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class OllamaMessage {

    /** The role of the message sender (system, user, assistant, tool). */
    @JsonProperty("role")
    private String role;

    /** The content of the message. */
    @JsonProperty("content")
    private String content;

    /**
     * The model's reasoning content, returned by thinking models when the request enables the
     * {@code think} option. In native Ollama {@code /api/chat} this is returned in {@code thinking};
     * some reasoning models or proxies expose it under {@code reasoning} or {@code reasoning_content}.
     *
     * <p>In Ollama's schema, {@code thinking} is an optional message field; AgentScope's
     * {@code OllamaResponseParser} extracts inbound reasoning into {@code ThinkingBlock}.
     */
    @JsonProperty("thinking")
    @JsonAlias({"reasoning", "reasoning_content"})
    private String thinking;

    /** List of base64-encoded images (optional). */
    @JsonProperty("images")
    private List<String> images;

    /** List of tool calls generated by the model (optional). */
    @JsonProperty("tool_calls")
    private List<OllamaToolCall> toolCalls;

    /** The tool call ID (required for tool messages). */
    @JsonProperty("tool_call_id")
    private String toolCallId;

    /** The name of the tool/function (optional/required for tool messages). */
    @JsonProperty("tool_name")
    private String name;

    public OllamaMessage() {}

    public OllamaMessage(String role, String content) {
        this.role = role;
        this.content = content;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getThinking() {
        return thinking;
    }

    public void setThinking(String thinking) {
        this.thinking = thinking;
    }

    public List<String> getImages() {
        return images;
    }

    public void setImages(List<String> images) {
        this.images = images;
    }

    public List<OllamaToolCall> getToolCalls() {
        return toolCalls;
    }

    public void setToolCalls(List<OllamaToolCall> toolCalls) {
        this.toolCalls = toolCalls;
    }

    public String getToolCallId() {
        return toolCallId;
    }

    public void setToolCallId(String toolCallId) {
        this.toolCallId = toolCallId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
