// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/asdp/asdp.proto

package asdp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigType identifies the type of configuration resource (analogous to xDS type_url).
type ConfigType int32

const (
	ConfigType_CONFIG_TYPE_UNSPECIFIED ConfigType = 0
	ConfigType_CONFIG_TYPE_AGENT       ConfigType = 1
	ConfigType_CONFIG_TYPE_TOOL        ConfigType = 2
	ConfigType_CONFIG_TYPE_SKILL       ConfigType = 3
	ConfigType_CONFIG_TYPE_OVERRIDE    ConfigType = 4
	ConfigType_CONFIG_TYPE_MODEL       ConfigType = 5
)

// Enum value maps for ConfigType.
var (
	ConfigType_name = map[int32]string{
		0: "CONFIG_TYPE_UNSPECIFIED",
		1: "CONFIG_TYPE_AGENT",
		2: "CONFIG_TYPE_TOOL",
		3: "CONFIG_TYPE_SKILL",
		4: "CONFIG_TYPE_OVERRIDE",
		5: "CONFIG_TYPE_MODEL",
	}
	ConfigType_value = map[string]int32{
		"CONFIG_TYPE_UNSPECIFIED": 0,
		"CONFIG_TYPE_AGENT":       1,
		"CONFIG_TYPE_TOOL":        2,
		"CONFIG_TYPE_SKILL":       3,
		"CONFIG_TYPE_OVERRIDE":    4,
		"CONFIG_TYPE_MODEL":       5,
	}
)

func (x ConfigType) Enum() *ConfigType {
	p := new(ConfigType)
	*p = x
	return p
}

func (x ConfigType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_asdp_asdp_proto_enumTypes[0].Descriptor()
}

func (ConfigType) Type() protoreflect.EnumType {
	return &file_internal_asdp_asdp_proto_enumTypes[0]
}

func (x ConfigType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigType.Descriptor instead.
func (ConfigType) EnumDescriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{0}
}

type Upstream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *UpstreamMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Upstream_Connect
	//	*Upstream_ConfigAck
	//	*Upstream_SessionReport
	//	*Upstream_TeamEvent
	//	*Upstream_Heartbeat
	//	*Upstream_EventReport
	//	*Upstream_ContextReport
	//	*Upstream_Inventory
	Payload       isUpstream_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upstream) Reset() {
	*x = Upstream{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upstream) ProtoMessage() {}

func (x *Upstream) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upstream.ProtoReflect.Descriptor instead.
func (*Upstream) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{0}
}

func (x *Upstream) GetMeta() *UpstreamMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Upstream) GetPayload() isUpstream_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Upstream) GetConnect() *ConnectRequest {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *Upstream) GetConfigAck() *ConfigAck {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_ConfigAck); ok {
			return x.ConfigAck
		}
	}
	return nil
}

func (x *Upstream) GetSessionReport() *SessionReport {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_SessionReport); ok {
			return x.SessionReport
		}
	}
	return nil
}

func (x *Upstream) GetTeamEvent() *TeamEventReport {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_TeamEvent); ok {
			return x.TeamEvent
		}
	}
	return nil
}

func (x *Upstream) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Upstream) GetEventReport() *EventReport {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_EventReport); ok {
			return x.EventReport
		}
	}
	return nil
}

func (x *Upstream) GetContextReport() *ContextReport {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_ContextReport); ok {
			return x.ContextReport
		}
	}
	return nil
}

func (x *Upstream) GetInventory() *InventoryReport {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_Inventory); ok {
			return x.Inventory
		}
	}
	return nil
}

type isUpstream_Payload interface {
	isUpstream_Payload()
}

type Upstream_Connect struct {
	Connect *ConnectRequest `protobuf:"bytes,10,opt,name=connect,proto3,oneof"`
}

type Upstream_ConfigAck struct {
	ConfigAck *ConfigAck `protobuf:"bytes,11,opt,name=config_ack,json=configAck,proto3,oneof"`
}

type Upstream_SessionReport struct {
	SessionReport *SessionReport `protobuf:"bytes,12,opt,name=session_report,json=sessionReport,proto3,oneof"`
}

type Upstream_TeamEvent struct {
	TeamEvent *TeamEventReport `protobuf:"bytes,13,opt,name=team_event,json=teamEvent,proto3,oneof"`
}

type Upstream_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,14,opt,name=heartbeat,proto3,oneof"`
}

type Upstream_EventReport struct {
	EventReport *EventReport `protobuf:"bytes,15,opt,name=event_report,json=eventReport,proto3,oneof"` // Level 2 event stream
}

type Upstream_ContextReport struct {
	ContextReport *ContextReport `protobuf:"bytes,16,opt,name=context_report,json=contextReport,proto3,oneof"` // Level 4 effective context
}

type Upstream_Inventory struct {
	Inventory *InventoryReport `protobuf:"bytes,17,opt,name=inventory,proto3,oneof"` // instance inventory (subagents / workspaces / health)
}

func (*Upstream_Connect) isUpstream_Payload() {}

func (*Upstream_ConfigAck) isUpstream_Payload() {}

func (*Upstream_SessionReport) isUpstream_Payload() {}

func (*Upstream_TeamEvent) isUpstream_Payload() {}

func (*Upstream_Heartbeat) isUpstream_Payload() {}

func (*Upstream_EventReport) isUpstream_Payload() {}

func (*Upstream_ContextReport) isUpstream_Payload() {}

func (*Upstream_Inventory) isUpstream_Payload() {}

type UpstreamMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamMeta) Reset() {
	*x = UpstreamMeta{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamMeta) ProtoMessage() {}

func (x *UpstreamMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamMeta.ProtoReflect.Descriptor instead.
func (*UpstreamMeta) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{1}
}

func (x *UpstreamMeta) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *UpstreamMeta) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *UpstreamMeta) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpstreamMeta) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Handshake (sent on connection establish, analogous to xDS initial DiscoveryRequest)
type ConnectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Runtime         string                 `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	SdkVersion      string                 `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	SessionAffinity string                 `protobuf:"bytes,4,opt,name=session_affinity,json=sessionAffinity,proto3" json:"session_affinity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *ConnectRequest) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *ConnectRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ConnectRequest) GetSessionAffinity() string {
	if x != nil {
		return x.SessionAffinity
	}
	return ""
}

// Config acknowledgement (analogous to xDS ACK/NACK)
type ConfigAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigType    ConfigType             `protobuf:"varint,1,opt,name=config_type,json=configType,proto3,enum=agentscope.protocol.v1.ConfigType" json:"config_type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Nonce         string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Accepted      bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason  string                 `protobuf:"bytes,5,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigAck) Reset() {
	*x = ConfigAck{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAck) ProtoMessage() {}

func (x *ConfigAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAck.ProtoReflect.Descriptor instead.
func (*ConfigAck) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigAck) GetConfigType() ConfigType {
	if x != nil {
		return x.ConfigType
	}
	return ConfigType_CONFIG_TYPE_UNSPECIFIED
}

func (x *ConfigAck) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigAck) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ConfigAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConfigAck) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

// Session state report (periodic batch, e.g. every 10s)
type SessionReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionSnapshot     `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionReport) Reset() {
	*x = SessionReport{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReport) ProtoMessage() {}

func (x *SessionReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReport.ProtoReflect.Descriptor instead.
func (*SessionReport) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{4}
}

func (x *SessionReport) GetSessions() []*SessionSnapshot {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Phase            string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	MessageCount     int32                  `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,4,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,5,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	ContextPressure  float64                `protobuf:"fixed64,6,opt,name=context_pressure,json=contextPressure,proto3" json:"context_pressure,omitempty"`
	TaskSummary      *TaskSummary           `protobuf:"bytes,7,opt,name=task_summary,json=taskSummary,proto3" json:"task_summary,omitempty"`
	TeamId           string                 `protobuf:"bytes,8,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TeamRole         string                 `protobuf:"bytes,9,opt,name=team_role,json=teamRole,proto3" json:"team_role,omitempty"`
	// Framework identification (Level 1 extension, see sdk-design.md §3.1)
	Framework        string `protobuf:"bytes,10,opt,name=framework,proto3" json:"framework,omitempty"` // "claude-agent-sdk" | "langchain" | "adk" | ...
	FrameworkVersion string `protobuf:"bytes,11,opt,name=framework_version,json=frameworkVersion,proto3" json:"framework_version,omitempty"`
	// Context change detection
	ContextHash           string `protobuf:"bytes,12,opt,name=context_hash,json=contextHash,proto3" json:"context_hash,omitempty"`                                  // SHA-256 (first 16 hex) of the effective context
	IsCompacted           bool   `protobuf:"varint,13,opt,name=is_compacted,json=isCompacted,proto3" json:"is_compacted,omitempty"`                                 // whether the context has been compacted
	EffectiveMessageCount int32  `protobuf:"varint,14,opt,name=effective_message_count,json=effectiveMessageCount,proto3" json:"effective_message_count,omitempty"` // effective messages after compaction (!= message_count)
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SessionSnapshot) Reset() {
	*x = SessionSnapshot{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSnapshot) ProtoMessage() {}

func (x *SessionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSnapshot.ProtoReflect.Descriptor instead.
func (*SessionSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{5}
}

func (x *SessionSnapshot) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionSnapshot) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SessionSnapshot) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SessionSnapshot) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *SessionSnapshot) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *SessionSnapshot) GetContextPressure() float64 {
	if x != nil {
		return x.ContextPressure
	}
	return 0
}

func (x *SessionSnapshot) GetTaskSummary() *TaskSummary {
	if x != nil {
		return x.TaskSummary
	}
	return nil
}

func (x *SessionSnapshot) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *SessionSnapshot) GetTeamRole() string {
	if x != nil {
		return x.TeamRole
	}
	return ""
}

func (x *SessionSnapshot) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *SessionSnapshot) GetFrameworkVersion() string {
	if x != nil {
		return x.FrameworkVersion
	}
	return ""
}

func (x *SessionSnapshot) GetContextHash() string {
	if x != nil {
		return x.ContextHash
	}
	return ""
}

func (x *SessionSnapshot) GetIsCompacted() bool {
	if x != nil {
		return x.IsCompacted
	}
	return false
}

func (x *SessionSnapshot) GetEffectiveMessageCount() int32 {
	if x != nil {
		return x.EffectiveMessageCount
	}
	return 0
}

type TaskSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Pending       int32                  `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	InProgress    int32                  `protobuf:"varint,3,opt,name=in_progress,json=inProgress,proto3" json:"in_progress,omitempty"`
	Completed     int32                  `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSummary) Reset() {
	*x = TaskSummary{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSummary) ProtoMessage() {}

func (x *TaskSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSummary.ProtoReflect.Descriptor instead.
func (*TaskSummary) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{6}
}

func (x *TaskSummary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TaskSummary) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *TaskSummary) GetInProgress() int32 {
	if x != nil {
		return x.InProgress
	}
	return 0
}

func (x *TaskSummary) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

// Team event report
type TeamEventReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	MemberName    string                 `protobuf:"bytes,3,opt,name=member_name,json=memberName,proto3" json:"member_name,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Detail        []byte                 `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamEventReport) Reset() {
	*x = TeamEventReport{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamEventReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamEventReport) ProtoMessage() {}

func (x *TeamEventReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamEventReport.ProtoReflect.Descriptor instead.
func (*TeamEventReport) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{7}
}

func (x *TeamEventReport) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamEventReport) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TeamEventReport) GetMemberName() string {
	if x != nil {
		return x.MemberName
	}
	return ""
}

func (x *TeamEventReport) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TeamEventReport) GetDetail() []byte {
	if x != nil {
		return x.Detail
	}
	return nil
}

// Heartbeat (bidirectional keepalive)
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{8}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Instance health reported by data plane
type InstanceHealth struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,3,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	CpuUsage       float64                `protobuf:"fixed64,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage    float64                `protobuf:"fixed64,5,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstanceHealth) Reset() {
	*x = InstanceHealth{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceHealth) ProtoMessage() {}

func (x *InstanceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceHealth.ProtoReflect.Descriptor instead.
func (*InstanceHealth) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{9}
}

func (x *InstanceHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *InstanceHealth) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InstanceHealth) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *InstanceHealth) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *InstanceHealth) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

// EventReport is the Level-2 event stream report (batched, e.g. every 5s or
// every 20 events). Written by the control plane into the session_events table.
type EventReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*SessionEventMsg     `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReport) Reset() {
	*x = EventReport{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReport) ProtoMessage() {}

func (x *EventReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReport.ProtoReflect.Descriptor instead.
func (*EventReport) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{10}
}

func (x *EventReport) GetEvents() []*SessionEventMsg {
	if x != nil {
		return x.Events
	}
	return nil
}

type SessionEventMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Seq           int32                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                                 // monotonically increasing per session; idempotency key
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`     // session_start | message | tool_call | tool_result | session_end | compaction
	OccurredAt    int64                  `protobuf:"varint,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // unix milliseconds
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`                                // user | assistant | system | tool
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                          // summary (recommended <= 500 chars), not full text
	ToolName      string                 `protobuf:"bytes,7,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolInput     []byte                 `protobuf:"bytes,8,opt,name=tool_input,json=toolInput,proto3" json:"tool_input,omitempty"`    // JSON, may be truncated
	ToolOutput    string                 `protobuf:"bytes,9,opt,name=tool_output,json=toolOutput,proto3" json:"tool_output,omitempty"` // summary
	TokensIn      int32                  `protobuf:"varint,10,opt,name=tokens_in,json=tokensIn,proto3" json:"tokens_in,omitempty"`
	TokensOut     int32                  `protobuf:"varint,11,opt,name=tokens_out,json=tokensOut,proto3" json:"tokens_out,omitempty"`
	DurationMs    int32                  `protobuf:"varint,12,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	FrameworkMeta []byte                 `protobuf:"bytes,13,opt,name=framework_meta,json=frameworkMeta,proto3" json:"framework_meta,omitempty"` // framework-private JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEventMsg) Reset() {
	*x = SessionEventMsg{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEventMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEventMsg) ProtoMessage() {}

func (x *SessionEventMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEventMsg.ProtoReflect.Descriptor instead.
func (*SessionEventMsg) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{11}
}

func (x *SessionEventMsg) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEventMsg) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SessionEventMsg) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SessionEventMsg) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

func (x *SessionEventMsg) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SessionEventMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SessionEventMsg) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *SessionEventMsg) GetToolInput() []byte {
	if x != nil {
		return x.ToolInput
	}
	return nil
}

func (x *SessionEventMsg) GetToolOutput() string {
	if x != nil {
		return x.ToolOutput
	}
	return ""
}

func (x *SessionEventMsg) GetTokensIn() int32 {
	if x != nil {
		return x.TokensIn
	}
	return 0
}

func (x *SessionEventMsg) GetTokensOut() int32 {
	if x != nil {
		return x.TokensOut
	}
	return 0
}

func (x *SessionEventMsg) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *SessionEventMsg) GetFrameworkMeta() []byte {
	if x != nil {
		return x.FrameworkMeta
	}
	return nil
}

// ContextReport is the Level-4 effective-context report, pushed on compaction
// or when context_hash changes (debounced). Written into context_snapshots.
type ContextReport struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ContextHash          string                 `protobuf:"bytes,2,opt,name=context_hash,json=contextHash,proto3" json:"context_hash,omitempty"`
	CapturedAt           int64                  `protobuf:"varint,3,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"` // unix milliseconds
	SystemPrompt         string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Messages             []byte                 `protobuf:"bytes,5,opt,name=messages,proto3" json:"messages,omitempty"` // JSON array of {role, content, is_compaction?}
	Tools                []byte                 `protobuf:"bytes,6,opt,name=tools,proto3" json:"tools,omitempty"`       // JSON array of ToolInfo
	IsCompacted          bool                   `protobuf:"varint,7,opt,name=is_compacted,json=isCompacted,proto3" json:"is_compacted,omitempty"`
	CompactionSummary    string                 `protobuf:"bytes,8,opt,name=compaction_summary,json=compactionSummary,proto3" json:"compaction_summary,omitempty"`
	OriginalMessageCount int32                  `protobuf:"varint,9,opt,name=original_message_count,json=originalMessageCount,proto3" json:"original_message_count,omitempty"`
	CompactedAt          int64                  `protobuf:"varint,10,opt,name=compacted_at,json=compactedAt,proto3" json:"compacted_at,omitempty"` // unix milliseconds
	TotalTokens          int32                  `protobuf:"varint,11,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	MaxTokens            int32                  `protobuf:"varint,12,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Framework            string                 `protobuf:"bytes,13,opt,name=framework,proto3" json:"framework,omitempty"`
	FrameworkState       []byte                 `protobuf:"bytes,14,opt,name=framework_state,json=frameworkState,proto3" json:"framework_state,omitempty"` // framework-private JSON (graph state, session metadata, ...)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ContextReport) Reset() {
	*x = ContextReport{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextReport) ProtoMessage() {}

func (x *ContextReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextReport.ProtoReflect.Descriptor instead.
func (*ContextReport) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{12}
}

func (x *ContextReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ContextReport) GetContextHash() string {
	if x != nil {
		return x.ContextHash
	}
	return ""
}

func (x *ContextReport) GetCapturedAt() int64 {
	if x != nil {
		return x.CapturedAt
	}
	return 0
}

func (x *ContextReport) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ContextReport) GetMessages() []byte {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ContextReport) GetTools() []byte {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ContextReport) GetIsCompacted() bool {
	if x != nil {
		return x.IsCompacted
	}
	return false
}

func (x *ContextReport) GetCompactionSummary() string {
	if x != nil {
		return x.CompactionSummary
	}
	return ""
}

func (x *ContextReport) GetOriginalMessageCount() int32 {
	if x != nil {
		return x.OriginalMessageCount
	}
	return 0
}

func (x *ContextReport) GetCompactedAt() int64 {
	if x != nil {
		return x.CompactedAt
	}
	return 0
}

func (x *ContextReport) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ContextReport) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ContextReport) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *ContextReport) GetFrameworkState() []byte {
	if x != nil {
		return x.FrameworkState
	}
	return nil
}

// InventoryReport carries the instance-level runtime inventory: subagents,
// workspaces and health. Sent right after connect, then on change or at the
// Level-1 cadence.
type InventoryReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subagents     []*SubagentInfo        `protobuf:"bytes,1,rep,name=subagents,proto3" json:"subagents,omitempty"`
	Workspaces    []*WorkspaceInfo       `protobuf:"bytes,2,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	Health        *InstanceHealth        `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReport) Reset() {
	*x = InventoryReport{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReport) ProtoMessage() {}

func (x *InventoryReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReport.ProtoReflect.Descriptor instead.
func (*InventoryReport) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{13}
}

func (x *InventoryReport) GetSubagents() []*SubagentInfo {
	if x != nil {
		return x.Subagents
	}
	return nil
}

func (x *InventoryReport) GetWorkspaces() []*WorkspaceInfo {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *InventoryReport) GetHealth() *InstanceHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

type SubagentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tools         []string               `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	WorkspaceMode string                 `protobuf:"bytes,4,opt,name=workspace_mode,json=workspaceMode,proto3" json:"workspace_mode,omitempty"` // isolated | shared
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`                                          // remote subagent endpoint, if any
	InvokeCount   int64                  `protobuf:"varint,6,opt,name=invoke_count,json=invokeCount,proto3" json:"invoke_count,omitempty"`
	LastInvokedAt int64                  `protobuf:"varint,7,opt,name=last_invoked_at,json=lastInvokedAt,proto3" json:"last_invoked_at,omitempty"` // unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubagentInfo) Reset() {
	*x = SubagentInfo{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubagentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubagentInfo) ProtoMessage() {}

func (x *SubagentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubagentInfo.ProtoReflect.Descriptor instead.
func (*SubagentInfo) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{14}
}

func (x *SubagentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubagentInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SubagentInfo) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *SubagentInfo) GetWorkspaceMode() string {
	if x != nil {
		return x.WorkspaceMode
	}
	return ""
}

func (x *SubagentInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SubagentInfo) GetInvokeCount() int64 {
	if x != nil {
		return x.InvokeCount
	}
	return 0
}

func (x *SubagentInfo) GetLastInvokedAt() int64 {
	if x != nil {
		return x.LastInvokedAt
	}
	return 0
}

type WorkspaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // isolated | shared | readonly
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	OwnerRef      string                 `protobuf:"bytes,4,opt,name=owner_ref,json=ownerRef,proto3" json:"owner_ref,omitempty"` // session_id or subagent name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceInfo) Reset() {
	*x = WorkspaceInfo{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceInfo) ProtoMessage() {}

func (x *WorkspaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceInfo.ProtoReflect.Descriptor instead.
func (*WorkspaceInfo) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{15}
}

func (x *WorkspaceInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WorkspaceInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *WorkspaceInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *WorkspaceInfo) GetOwnerRef() string {
	if x != nil {
		return x.OwnerRef
	}
	return ""
}

type Downstream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Downstream_ConnectAck
	//	*Downstream_ConfigPush
	//	*Downstream_SessionCmd
	//	*Downstream_TeamEvent
	//	*Downstream_Heartbeat
	Payload       isDownstream_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Downstream) Reset() {
	*x = Downstream{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Downstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Downstream) ProtoMessage() {}

func (x *Downstream) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Downstream.ProtoReflect.Descriptor instead.
func (*Downstream) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{16}
}

func (x *Downstream) GetPayload() isDownstream_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Downstream) GetConnectAck() *ConnectResponse {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_ConnectAck); ok {
			return x.ConnectAck
		}
	}
	return nil
}

func (x *Downstream) GetConfigPush() *ConfigPush {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_ConfigPush); ok {
			return x.ConfigPush
		}
	}
	return nil
}

func (x *Downstream) GetSessionCmd() *SessionCommand {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_SessionCmd); ok {
			return x.SessionCmd
		}
	}
	return nil
}

func (x *Downstream) GetTeamEvent() *TeamEvent {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_TeamEvent); ok {
			return x.TeamEvent
		}
	}
	return nil
}

func (x *Downstream) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isDownstream_Payload interface {
	isDownstream_Payload()
}

type Downstream_ConnectAck struct {
	ConnectAck *ConnectResponse `protobuf:"bytes,10,opt,name=connect_ack,json=connectAck,proto3,oneof"`
}

type Downstream_ConfigPush struct {
	ConfigPush *ConfigPush `protobuf:"bytes,11,opt,name=config_push,json=configPush,proto3,oneof"`
}

type Downstream_SessionCmd struct {
	SessionCmd *SessionCommand `protobuf:"bytes,12,opt,name=session_cmd,json=sessionCmd,proto3,oneof"`
}

type Downstream_TeamEvent struct {
	TeamEvent *TeamEvent `protobuf:"bytes,13,opt,name=team_event,json=teamEvent,proto3,oneof"`
}

type Downstream_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,14,opt,name=heartbeat,proto3,oneof"`
}

func (*Downstream_ConnectAck) isDownstream_Payload() {}

func (*Downstream_ConfigPush) isDownstream_Payload() {}

func (*Downstream_SessionCmd) isDownstream_Payload() {}

func (*Downstream_TeamEvent) isDownstream_Payload() {}

func (*Downstream_Heartbeat) isDownstream_Payload() {}

type ConnectResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Accepted            bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason        string                 `protobuf:"bytes,2,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	ControlPlaneVersion string                 `protobuf:"bytes,3,opt,name=control_plane_version,json=controlPlaneVersion,proto3" json:"control_plane_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{17}
}

func (x *ConnectResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConnectResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *ConnectResponse) GetControlPlaneVersion() string {
	if x != nil {
		return x.ControlPlaneVersion
	}
	return ""
}

// Config push (analogous to xDS DiscoveryResponse)
type ConfigPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigType    ConfigType             `protobuf:"varint,1,opt,name=config_type,json=configType,proto3,enum=agentscope.protocol.v1.ConfigType" json:"config_type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Resources     []byte                 `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	Nonce         string                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPush) Reset() {
	*x = ConfigPush{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPush) ProtoMessage() {}

func (x *ConfigPush) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPush.ProtoReflect.Descriptor instead.
func (*ConfigPush) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{18}
}

func (x *ConfigPush) GetConfigType() ConfigType {
	if x != nil {
		return x.ConfigType
	}
	return ConfigType_CONFIG_TYPE_UNSPECIFIED
}

func (x *ConfigPush) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigPush) GetResources() []byte {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ConfigPush) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type SessionCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Params        []byte                 `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCommand) Reset() {
	*x = SessionCommand{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCommand) ProtoMessage() {}

func (x *SessionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCommand.ProtoReflect.Descriptor instead.
func (*SessionCommand) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{19}
}

func (x *SessionCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SessionCommand) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type TeamEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	MemberName    string                 `protobuf:"bytes,3,opt,name=member_name,json=memberName,proto3" json:"member_name,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamEvent) Reset() {
	*x = TeamEvent{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamEvent) ProtoMessage() {}

func (x *TeamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamEvent.ProtoReflect.Descriptor instead.
func (*TeamEvent) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{20}
}

func (x *TeamEvent) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TeamEvent) GetMemberName() string {
	if x != nil {
		return x.MemberName
	}
	return ""
}

func (x *TeamEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TeamEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TeamEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_internal_asdp_asdp_proto protoreflect.FileDescriptor

const file_internal_asdp_asdp_proto_rawDesc = "" +
	"\n" +
	"\x18internal/asdp/asdp.proto\x12\x16agentscope.protocol.v1\"\x97\x05\n" +
	"\bUpstream\x128\n" +
	"\x04meta\x18\x01 \x01(\v2$.agentscope.protocol.v1.UpstreamMetaR\x04meta\x12B\n" +
	"\aconnect\x18\n" +
	" \x01(\v2&.agentscope.protocol.v1.ConnectRequestH\x00R\aconnect\x12B\n" +
	"\n" +
	"config_ack\x18\v \x01(\v2!.agentscope.protocol.v1.ConfigAckH\x00R\tconfigAck\x12N\n" +
	"\x0esession_report\x18\f \x01(\v2%.agentscope.protocol.v1.SessionReportH\x00R\rsessionReport\x12H\n" +
	"\n" +
	"team_event\x18\r \x01(\v2'.agentscope.protocol.v1.TeamEventReportH\x00R\tteamEvent\x12A\n" +
	"\theartbeat\x18\x0e \x01(\v2!.agentscope.protocol.v1.HeartbeatH\x00R\theartbeat\x12H\n" +
	"\fevent_report\x18\x0f \x01(\v2#.agentscope.protocol.v1.EventReportH\x00R\veventReport\x12N\n" +
	"\x0econtext_report\x18\x10 \x01(\v2%.agentscope.protocol.v1.ContextReportH\x00R\rcontextReport\x12G\n" +
	"\tinventory\x18\x11 \x01(\v2'.agentscope.protocol.v1.InventoryReportH\x00R\tinventoryB\t\n" +
	"\apayload\"\x8a\x01\n" +
	"\fUpstreamMeta\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x9a\x01\n" +
	"\x0eConnectRequest\x12\x18\n" +
	"\aruntime\x18\x01 \x01(\tR\aruntime\x12\x1f\n" +
	"\vsdk_version\x18\x02 \x01(\tR\n" +
	"sdkVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12)\n" +
	"\x10session_affinity\x18\x04 \x01(\tR\x0fsessionAffinity\"\xc1\x01\n" +
	"\tConfigAck\x12C\n" +
	"\vconfig_type\x18\x01 \x01(\x0e2\".agentscope.protocol.v1.ConfigTypeR\n" +
	"configType\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x05 \x01(\tR\frejectReason\"T\n" +
	"\rSessionReport\x12C\n" +
	"\bsessions\x18\x01 \x03(\v2'.agentscope.protocol.v1.SessionSnapshotR\bsessions\"\xaf\x04\n" +
	"\x0fSessionSnapshot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x05R\fmessageCount\x12#\n" +
	"\rprompt_tokens\x18\x04 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x05 \x01(\x03R\x10completionTokens\x12)\n" +
	"\x10context_pressure\x18\x06 \x01(\x01R\x0fcontextPressure\x12F\n" +
	"\ftask_summary\x18\a \x01(\v2#.agentscope.protocol.v1.TaskSummaryR\vtaskSummary\x12\x17\n" +
	"\ateam_id\x18\b \x01(\tR\x06teamId\x12\x1b\n" +
	"\tteam_role\x18\t \x01(\tR\bteamRole\x12\x1c\n" +
	"\tframework\x18\n" +
	" \x01(\tR\tframework\x12+\n" +
	"\x11framework_version\x18\v \x01(\tR\x10frameworkVersion\x12!\n" +
	"\fcontext_hash\x18\f \x01(\tR\vcontextHash\x12!\n" +
	"\fis_compacted\x18\r \x01(\bR\visCompacted\x126\n" +
	"\x17effective_message_count\x18\x0e \x01(\x05R\x15effectiveMessageCount\"|\n" +
	"\vTaskSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\apending\x18\x02 \x01(\x05R\apending\x12\x1f\n" +
	"\vin_progress\x18\x03 \x01(\x05R\n" +
	"inProgress\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\x05R\tcompleted\"\x9b\x01\n" +
	"\x0fTeamEventReport\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1f\n" +
	"\vmember_name\x18\x03 \x01(\tR\n" +
	"memberName\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\fR\x06detail\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xab\x01\n" +
	"\x0eInstanceHealth\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12'\n" +
	"\x0factive_sessions\x18\x03 \x01(\x05R\x0eactiveSessions\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x05 \x01(\x01R\vmemoryUsage\"N\n" +
	"\vEventReport\x12?\n" +
	"\x06events\x18\x01 \x03(\v2'.agentscope.protocol.v1.SessionEventMsgR\x06events\"\x91\x03\n" +
	"\x0fSessionEventMsg\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1f\n" +
	"\voccurred_at\x18\x04 \x01(\x03R\n" +
	"occurredAt\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1b\n" +
	"\ttool_name\x18\a \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"tool_input\x18\b \x01(\fR\ttoolInput\x12\x1f\n" +
	"\vtool_output\x18\t \x01(\tR\n" +
	"toolOutput\x12\x1b\n" +
	"\ttokens_in\x18\n" +
	" \x01(\x05R\btokensIn\x12\x1d\n" +
	"\n" +
	"tokens_out\x18\v \x01(\x05R\ttokensOut\x12\x1f\n" +
	"\vduration_ms\x18\f \x01(\x05R\n" +
	"durationMs\x12%\n" +
	"\x0eframework_meta\x18\r \x01(\fR\rframeworkMeta\"\xfd\x03\n" +
	"\rContextReport\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fcontext_hash\x18\x02 \x01(\tR\vcontextHash\x12\x1f\n" +
	"\vcaptured_at\x18\x03 \x01(\x03R\n" +
	"capturedAt\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12\x1a\n" +
	"\bmessages\x18\x05 \x01(\fR\bmessages\x12\x14\n" +
	"\x05tools\x18\x06 \x01(\fR\x05tools\x12!\n" +
	"\fis_compacted\x18\a \x01(\bR\visCompacted\x12-\n" +
	"\x12compaction_summary\x18\b \x01(\tR\x11compactionSummary\x124\n" +
	"\x16original_message_count\x18\t \x01(\x05R\x14originalMessageCount\x12!\n" +
	"\fcompacted_at\x18\n" +
	" \x01(\x03R\vcompactedAt\x12!\n" +
	"\ftotal_tokens\x18\v \x01(\x05R\vtotalTokens\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\f \x01(\x05R\tmaxTokens\x12\x1c\n" +
	"\tframework\x18\r \x01(\tR\tframework\x12'\n" +
	"\x0fframework_state\x18\x0e \x01(\fR\x0eframeworkState\"\xdc\x01\n" +
	"\x0fInventoryReport\x12B\n" +
	"\tsubagents\x18\x01 \x03(\v2$.agentscope.protocol.v1.SubagentInfoR\tsubagents\x12E\n" +
	"\n" +
	"workspaces\x18\x02 \x03(\v2%.agentscope.protocol.v1.WorkspaceInfoR\n" +
	"workspaces\x12>\n" +
	"\x06health\x18\x03 \x01(\v2&.agentscope.protocol.v1.InstanceHealthR\x06health\"\xde\x01\n" +
	"\fSubagentInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05tools\x18\x03 \x03(\tR\x05tools\x12%\n" +
	"\x0eworkspace_mode\x18\x04 \x01(\tR\rworkspaceMode\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12!\n" +
	"\finvoke_count\x18\x06 \x01(\x03R\vinvokeCount\x12&\n" +
	"\x0flast_invoked_at\x18\a \x01(\x03R\rlastInvokedAt\"s\n" +
	"\rWorkspaceInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\towner_ref\x18\x04 \x01(\tR\bownerRef\"\xfc\x02\n" +
	"\n" +
	"Downstream\x12J\n" +
	"\vconnect_ack\x18\n" +
	" \x01(\v2'.agentscope.protocol.v1.ConnectResponseH\x00R\n" +
	"connectAck\x12E\n" +
	"\vconfig_push\x18\v \x01(\v2\".agentscope.protocol.v1.ConfigPushH\x00R\n" +
	"configPush\x12I\n" +
	"\vsession_cmd\x18\f \x01(\v2&.agentscope.protocol.v1.SessionCommandH\x00R\n" +
	"sessionCmd\x12B\n" +
	"\n" +
	"team_event\x18\r \x01(\v2!.agentscope.protocol.v1.TeamEventH\x00R\tteamEvent\x12A\n" +
	"\theartbeat\x18\x0e \x01(\v2!.agentscope.protocol.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x86\x01\n" +
	"\x0fConnectResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x02 \x01(\tR\frejectReason\x122\n" +
	"\x15control_plane_version\x18\x03 \x01(\tR\x13controlPlaneVersion\"\x9f\x01\n" +
	"\n" +
	"ConfigPush\x12C\n" +
	"\vconfig_type\x18\x01 \x01(\x0e2\".agentscope.protocol.v1.ConfigTypeR\n" +
	"configType\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tresources\x18\x03 \x01(\fR\tresources\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\"a\n" +
	"\x0eSessionCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\"\xb5\x01\n" +
	"\tTeamEvent\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1f\n" +
	"\vmember_name\x18\x03 \x01(\tR\n" +
	"memberName\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp*\x9e\x01\n" +
	"\n" +
	"ConfigType\x12\x1b\n" +
	"\x17CONFIG_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CONFIG_TYPE_AGENT\x10\x01\x12\x14\n" +
	"\x10CONFIG_TYPE_TOOL\x10\x02\x12\x15\n" +
	"\x11CONFIG_TYPE_SKILL\x10\x03\x12\x18\n" +
	"\x14CONFIG_TYPE_OVERRIDE\x10\x04\x12\x15\n" +
	"\x11CONFIG_TYPE_MODEL\x10\x052l\n" +
	"\x15AgentDataPlaneService\x12S\n" +
	"\aConnect\x12 .agentscope.protocol.v1.Upstream\x1a\".agentscope.protocol.v1.Downstream(\x010\x01BAZ?github.com/agentscope/agentscope-go/control-plane/internal/asdpb\x06proto3"

var (
	file_internal_asdp_asdp_proto_rawDescOnce sync.Once
	file_internal_asdp_asdp_proto_rawDescData []byte
)

func file_internal_asdp_asdp_proto_rawDescGZIP() []byte {
	file_internal_asdp_asdp_proto_rawDescOnce.Do(func() {
		file_internal_asdp_asdp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_asdp_asdp_proto_rawDesc), len(file_internal_asdp_asdp_proto_rawDesc)))
	})
	return file_internal_asdp_asdp_proto_rawDescData
}

var file_internal_asdp_asdp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_asdp_asdp_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_internal_asdp_asdp_proto_goTypes = []any{
	(ConfigType)(0),         // 0: agentscope.protocol.v1.ConfigType
	(*Upstream)(nil),        // 1: agentscope.protocol.v1.Upstream
	(*UpstreamMeta)(nil),    // 2: agentscope.protocol.v1.UpstreamMeta
	(*ConnectRequest)(nil),  // 3: agentscope.protocol.v1.ConnectRequest
	(*ConfigAck)(nil),       // 4: agentscope.protocol.v1.ConfigAck
	(*SessionReport)(nil),   // 5: agentscope.protocol.v1.SessionReport
	(*SessionSnapshot)(nil), // 6: agentscope.protocol.v1.SessionSnapshot
	(*TaskSummary)(nil),     // 7: agentscope.protocol.v1.TaskSummary
	(*TeamEventReport)(nil), // 8: agentscope.protocol.v1.TeamEventReport
	(*Heartbeat)(nil),       // 9: agentscope.protocol.v1.Heartbeat
	(*InstanceHealth)(nil),  // 10: agentscope.protocol.v1.InstanceHealth
	(*EventReport)(nil),     // 11: agentscope.protocol.v1.EventReport
	(*SessionEventMsg)(nil), // 12: agentscope.protocol.v1.SessionEventMsg
	(*ContextReport)(nil),   // 13: agentscope.protocol.v1.ContextReport
	(*InventoryReport)(nil), // 14: agentscope.protocol.v1.InventoryReport
	(*SubagentInfo)(nil),    // 15: agentscope.protocol.v1.SubagentInfo
	(*WorkspaceInfo)(nil),   // 16: agentscope.protocol.v1.WorkspaceInfo
	(*Downstream)(nil),      // 17: agentscope.protocol.v1.Downstream
	(*ConnectResponse)(nil), // 18: agentscope.protocol.v1.ConnectResponse
	(*ConfigPush)(nil),      // 19: agentscope.protocol.v1.ConfigPush
	(*SessionCommand)(nil),  // 20: agentscope.protocol.v1.SessionCommand
	(*TeamEvent)(nil),       // 21: agentscope.protocol.v1.TeamEvent
}
var file_internal_asdp_asdp_proto_depIdxs = []int32{
	2,  // 0: agentscope.protocol.v1.Upstream.meta:type_name -> agentscope.protocol.v1.UpstreamMeta
	3,  // 1: agentscope.protocol.v1.Upstream.connect:type_name -> agentscope.protocol.v1.ConnectRequest
	4,  // 2: agentscope.protocol.v1.Upstream.config_ack:type_name -> agentscope.protocol.v1.ConfigAck
	5,  // 3: agentscope.protocol.v1.Upstream.session_report:type_name -> agentscope.protocol.v1.SessionReport
	8,  // 4: agentscope.protocol.v1.Upstream.team_event:type_name -> agentscope.protocol.v1.TeamEventReport
	9,  // 5: agentscope.protocol.v1.Upstream.heartbeat:type_name -> agentscope.protocol.v1.Heartbeat
	11, // 6: agentscope.protocol.v1.Upstream.event_report:type_name -> agentscope.protocol.v1.EventReport
	13, // 7: agentscope.protocol.v1.Upstream.context_report:type_name -> agentscope.protocol.v1.ContextReport
	14, // 8: agentscope.protocol.v1.Upstream.inventory:type_name -> agentscope.protocol.v1.InventoryReport
	0,  // 9: agentscope.protocol.v1.ConfigAck.config_type:type_name -> agentscope.protocol.v1.ConfigType
	6,  // 10: agentscope.protocol.v1.SessionReport.sessions:type_name -> agentscope.protocol.v1.SessionSnapshot
	7,  // 11: agentscope.protocol.v1.SessionSnapshot.task_summary:type_name -> agentscope.protocol.v1.TaskSummary
	12, // 12: agentscope.protocol.v1.EventReport.events:type_name -> agentscope.protocol.v1.SessionEventMsg
	15, // 13: agentscope.protocol.v1.InventoryReport.subagents:type_name -> agentscope.protocol.v1.SubagentInfo
	16, // 14: agentscope.protocol.v1.InventoryReport.workspaces:type_name -> agentscope.protocol.v1.WorkspaceInfo
	10, // 15: agentscope.protocol.v1.InventoryReport.health:type_name -> agentscope.protocol.v1.InstanceHealth
	18, // 16: agentscope.protocol.v1.Downstream.connect_ack:type_name -> agentscope.protocol.v1.ConnectResponse
	19, // 17: agentscope.protocol.v1.Downstream.config_push:type_name -> agentscope.protocol.v1.ConfigPush
	20, // 18: agentscope.protocol.v1.Downstream.session_cmd:type_name -> agentscope.protocol.v1.SessionCommand
	21, // 19: agentscope.protocol.v1.Downstream.team_event:type_name -> agentscope.protocol.v1.TeamEvent
	9,  // 20: agentscope.protocol.v1.Downstream.heartbeat:type_name -> agentscope.protocol.v1.Heartbeat
	0,  // 21: agentscope.protocol.v1.ConfigPush.config_type:type_name -> agentscope.protocol.v1.ConfigType
	1,  // 22: agentscope.protocol.v1.AgentDataPlaneService.Connect:input_type -> agentscope.protocol.v1.Upstream
	17, // 23: agentscope.protocol.v1.AgentDataPlaneService.Connect:output_type -> agentscope.protocol.v1.Downstream
	23, // [23:24] is the sub-list for method output_type
	22, // [22:23] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_internal_asdp_asdp_proto_init() }
func file_internal_asdp_asdp_proto_init() {
	if File_internal_asdp_asdp_proto != nil {
		return
	}
	file_internal_asdp_asdp_proto_msgTypes[0].OneofWrappers = []any{
		(*Upstream_Connect)(nil),
		(*Upstream_ConfigAck)(nil),
		(*Upstream_SessionReport)(nil),
		(*Upstream_TeamEvent)(nil),
		(*Upstream_Heartbeat)(nil),
		(*Upstream_EventReport)(nil),
		(*Upstream_ContextReport)(nil),
		(*Upstream_Inventory)(nil),
	}
	file_internal_asdp_asdp_proto_msgTypes[16].OneofWrappers = []any{
		(*Downstream_ConnectAck)(nil),
		(*Downstream_ConfigPush)(nil),
		(*Downstream_SessionCmd)(nil),
		(*Downstream_TeamEvent)(nil),
		(*Downstream_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_asdp_asdp_proto_rawDesc), len(file_internal_asdp_asdp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_asdp_asdp_proto_goTypes,
		DependencyIndexes: file_internal_asdp_asdp_proto_depIdxs,
		EnumInfos:         file_internal_asdp_asdp_proto_enumTypes,
		MessageInfos:      file_internal_asdp_asdp_proto_msgTypes,
	}.Build()
	File_internal_asdp_asdp_proto = out.File
	file_internal_asdp_asdp_proto_goTypes = nil
	file_internal_asdp_asdp_proto_depIdxs = nil
}
